apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "cl-adapter.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "cl-adapter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ cat (.Values.envVars | toString) (.Values.envSecrets | toString) | sha256sum | quote }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "cl-adapter.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.name }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ print .Values.image.repository (hasPrefix "sha256:" .Values.image.tag | ternary "@" ":") .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
            - name: metrics
              containerPort: {{ .Values.envVars.METRICS_PORT | default 9080 }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- if eq (.Values.envVars.CACHE_TYPE | default "") "redis" }}
            - name: CACHE_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.cache.redis.secretName }}
                  key: {{ .Values.cache.redis.secretKey }}
            {{- end }}
            {{- range $envKey, $envValue := .Values.envVars }}
            - name: {{ $envKey }}
              value: {{ $envValue | quote }}
            {{- end }}
          {{- if .Values.envSecrets }}
          envFrom:
            - secretRef:
                name: {{ .Values.name }}
          {{- end }}
