apiVersion: v1
kind: Service
metadata:
  # "adapter-" used due to DNS-1035 RFC requiring first character to be a letter (so no 1forge)
  name: adapter-{{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "cl-adapter.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "cl-adapter.selectorLabels" . | nindent 4 }}
